---
title: "Thema 2: Mathematische Grundlagen"
subtitle: "QM2, ROS, Kap. 3"
author: Prof. Sauer
date: WiSe 21
lang: de-DE
bibliography: /Users/sebastiansaueruser/Google Drive/Literatur/refmgt/library-ses.bib
institute: AWM, HS Ansbach
header-includes:
- \usepackage{booktabs}
output:
  beamer_presentation:
    toc: true
    theme: "Berkeley"
    #colortheme: "dolphin"
    # fonttheme: "structurebold"
    keep_tex: true
    includes:
      in_header: preamble.tex    
---


# Multiplikative Modelle


## "Normale" Regression: additiv, linear


$$y = b0 + b_1x_1 + b_2 x_2 + \ldots + b_k x_k + \epsilon$$


## LogY-Regression: Exponenzielles Wachstum


$log(y) = a + bx$

$y= Ae^{bx}$ mit $A=e^a$

$e$ ist die Eulersche Zahl, $2.71...$



## Beispiele für exponentielle Zusammenhänge

- Eine Bakterienmenge verdoppelt sich jeden Tag
- Pro Jahr erzielt eine Kapitalanlage 10% Zinsen
- Während einer bestimmten Periode verdoppelten sich die Coronafälle alle 10 Tage
- Die Menge der Vitamine in einem Lebensmittel verringert sich pro Zeiteinheit um den Faktor $k$



## Exponentielles Wachstum wächst stark

Beim exponentiellen Wachstum wächst eine Größe pro Zeitabschnitt immer um denselben Faktor.

Die Änderung einer Größe $A$ pro Zeitabschnitt $t$ ist proportional[^note] zum Bestand von $A$.

Exponentielles Wachstum wächst (ab einem bestimmten Zeitpunkt) sehr stark und wird daher leicht unterschätzt.

[^note]: Proportional bedeutet, Verdopplung (Verdreifachung, Vervierfachung...) einer Größe ist stets mit der Verdopplung (Verdreifachung, Vervierfachung, ...) der anderen Größe verbunden. So ist der Kreisumfang proportional zum Kreisdurchmesser mit dem Proportionalitätsfaktor 3.14.


## Aber was ist der Logarithmus?



\begin{alertblock}{Definition}
Seien $a,b > 0$ mit $b \ne 1$.

Die eindeutig bestimmte Zahl $x \in \mathbb{R}$ 
 mit $b^x=a$ heißt Logarithmus von $a$ zur Basis $b$. Sie wird mit $x = log_b(a)$ bezeichnet.

\end{alertblock}


[@cramer_vorkurs_2015.]



## Beispiele zum Logarithmus


::: columns

:::: column
### Basis 10
- $\log_{10}(10) = 1$
- $\log_{10}(100) = 2$
- $\log_{10}(1000) = 3$
::::

:::: column
### Basis 2
- $\log_{2}(2) = 1$
- $\log_{2}(4) = 2$
- $\log_{2}(8) = 3$
::::

:::

# Hinweise


## Lehrbuch und Homepage des Lehrbuchs

Dieses Skript bezieht sich auf ausgewählte Kapitel dieses Lehrbuchs: @gelman_regression_2021

Das Buch ist im Skript mit "ROS" abgekürzt.

Weitere Literaturhinweise sind am Ende der jeweiligen Kapitel des Lehrbuchs angegeben.

R-Code zum Buch findet sich auf der [Homepage](https://avehtari.github.io/ROS-Examples/examples.html) des Buchs.




## Literatur





<div id="refs"></div>



