---
params:
  kapitel_name: "Gaussmodelle: Schätzen einer metrischen Variablen"
  kapitel_nr: 4

title: "`r params$kapitel_name`"
subtitle: "`r paste0('Kapitel ', params$kapitel_nr)`"
#date: WiSe 21

#institute: AWM, HS Ansbach
output:
  xaringan::moon_reader:
    keep_md: false
    css: ["my-css.css","xaringan-themer.css",  "hygge", "default-fonts"]
    lib_dir: libs
    seal: true
    nature:
      titleSlideClass: ["right", "bottom", "test"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r QM2-Thema4-Gaussmodelle-1, child="children/Setup.Rmd"}
```


```{r}
book <- "Statistical Rethinking, Kapitel 4.1 - 4.3"
```

```{r set-fig-path-per-chapter}
knitr::opts_chunk$set(
   fig.path = paste0("Kapitel_", params$kapitel_nr,"_chunk-img/")
   )
```




## Gliederung



</br>
</br>
</br>

.xxlarge[
1. [Teil 1: Verteilungen](#verteilungen)

2. [Teil 2: Gauss-Modelle: Wie groß sind die !Kung San?](#gaussmodelle)

3. [Hinweise](#hinweise)
]

---

## Software

Für dieses Thema benötigen Sie einige R-Pakete, die Sie wie folgt installieren können:

```{r install-libs, eval = FALSE, echo=TRUE}
pakete <- c("tidyverse", "rstan", "rstanarm", "bayesplot")

install.packages(pakete)
```

Für `rstan` wird [weitere Software](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) benötigt.



---

```{r QM2-Thema4-Gaussmodelle-2, eval = TRUE, child="children/Normalverteilung.Rmd"}
```



```{r QM2-Thema4-Gaussmodelle-3, eval = TRUE, child="children/Kung.Rmd"}
```



```{r QM2-Thema4-Gaussmodelle-3, eval = TRUE, child="children/Hinweise.Rmd"}
```
