---
params:
  kapitel_name: "Forschungsfragen f체r bin채re AV" 
  kapitel_nr: 9

title: "`r params$kapitel_name`"
subtitle: "`r  paste0('Kapitel ', params$kapitel_nr)`"

output:
  xaringan::moon_reader:
    keep_md: false
    css: ["my-css.css","xaringan-themer.css",  "hygge", "default-fonts"]
    lib_dir: libs
    seal: true
    nature:
      titleSlideClass: ["right", "bottom", "test"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---




```{r QM2-Thema4-Gaussmodelle-1, child="children/Setup.Rmd", eval = TRUE}
```


```{r}
book <- "Regression and other stories (Kap. 13); Statistical Rethinking (Kap. 10.2)"

```


```{r}
knitr::opts_chunk$set(
   fig.path = paste0("Kapitel_", params$kapitel_nr,"_chunk-img/")
   )
```




## Gliederung


</br>
</br>




.xlarge[
1. [Teil 1: Grundlagen der logistischen Regression](#teil-1)

2. [Teil 2: Metrische UV](#teil-2)

2. [Teil 3: Prioris](#teil-3)

2. [Teil 4: Bin채re UV](#teil-4)

2. [Teil 5: Modellg체te](#teil-5)

5. [Hinweise](#hinweise)
]




```{r source-funs-local}
source("https://raw.githubusercontent.com/sebastiansauer/QM2-Folien/main/R-Code/gg_simple_fancy_dag.R")
```






---


```{r QM2-Thema8-Teil1, eval = TRUE, child="children/Thema9-Teil1.Rmd"}
```


```{r QM2-Thema8-Teil2, eval = TRUE, child="children/Thema9-Teil2.Rmd"}
```



```{r QM2-Thema8-Teil3, eval = TRUE, child="children/Thema9-Teil3.Rmd"}
```





```{r QM2-Thema8-Teil4, eval = TRUE, child="children/Thema9-Teil4.Rmd"}
```



```{r QM2-Thema8-Teil5, eval = TRUE, child="children/Thema9-Teil5.Rmd"}
```



```{r QM2-Thema8-Hinweise, eval = TRUE, child="children/Hinweise.Rmd"}
```



