---
params:
  kapitel_name: "Abschluss" 
  kapitel_nr: 10 

title: "`r params$kapitel_name`"
subtitle: "`r  paste0('Kapitel ', params$kapitel_nr)`"

output:
  xaringan::moon_reader:
    keep_md: false
    css: ["my-css.css","xaringan-themer.css",  "hygge", "default-fonts"]
    lib_dir: libs
    seal: true
    nature:
      titleSlideClass: ["right", "bottom", "test"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---




```{r QM2-Thema10-1, child="children/Setup.Rmd", eval = TRUE}
```

---



name: gliederung

## Gliederung


</br>
</br>




.xlarge[
1. [Teil 1: Lieblingsfehler](#teil-1)

2. [Teil 2: Kochrezepte](#teil-2)

3. [Teil 3: Kerngedanken Bayes](#teil-3)

4. [Teil 4: Beispiele für Prüfungsaufgaben](#teil-4)

5. [Hinweise](#hinweise)
]






---


```{r QM2-Thema10-Teil1, eval = TRUE, child="children/Thema10-Teil1.Rmd"}
```

```{r QM2-Thema10-Teil2, eval = TRUE, child="children/Thema10-Teil2.Rmd"}
```

```{r QM2-Thema10-Teil3, eval = TRUE, child="children/Thema10-Teil3.Rmd"}
```

```{r QM2-Thema10-Teil4, eval = TRUE, child="children/Thema10-Teil4.Rmd"}
```



```{r QM2-Thema10-Hinweise, eval = TRUE, child="children/Hinweise.Rmd"}
```



