---
title: Stichproben aus der Posteriori-Verteilung ziehen
subtitle: QM2, Thema 3
#date: WiSe 21
#lang: de-DE
#bibliography: /Users/sebastiansaueruser/Google Drive/Literatur/refmgt/library-ses.bib
#institute: AWM, HS Ansbach
output:
  xaringan::moon_reader:
    keep_md: false
    css: ["my-css.css","xaringan-themer.css",  "hygge", "default-fonts"]
    lib_dir: libs
    seal: true
    nature:
      titleSlideClass: ["right", "bottom", "test"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    
---






```{r QM2-Thema4-Gaussmodelle-1, child="children/Setup.Rmd"}
```


```{r}
book <- "*Statistical Rethinking*, Kap. 3"
```



## Gliederung



.xlarge[
1. [Mit Stichproben die Post-Verteilung zusammenfassen](#teil-1)

2. [Mit Stichproben neue Beobachtungen simulieren](#teil-2)

3. [Hinweise](#hinweise)
]

---


```{r QM2-Thema3-Teil1, eval = TRUE, child="children/QM2-Thema3-Teil1.Rmd"}
```


```{r QM2-Thema3-Teil2, eval = TRUE, child="children/QM2-Thema3-Teil2.Rmd"}
```




```{r QM2-Thema4-Gaussmodelle-3, eval = TRUE, child="children/Hinweise.Rmd"}
```
