---
params:
  kapitel_name: "Deskriptive Forschungsfragen mit metrischer AV" 
  kapitel_nr: 6

title: "`r params$kapitel_name`"
subtitle: "`r  paste0('Kapitel ', params$kapitel_nr)`"
#date: WiSe 21

#institute: AWM, HS Ansbach
output:
  xaringan::moon_reader:
    keep_md: false
    css: ["my-css.css","xaringan-themer.css",  "hygge", "default-fonts"]
    lib_dir: libs
    seal: true
    nature:
      titleSlideClass: ["right", "bottom", "test"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---




```{r QM2-Thema4-Gaussmodelle-1, child="children/Setup.Rmd", eval = TRUE}
```


```{r}
book <- "Regression and other stories"
book_chap <- "10, 11 (jeweils in Auszügen)"
```


```{r}
knitr::opts_chunk$set(
   fig.path = paste0("Kapitel_", params$kapitel_nr,"_chunk-img/")
   )
```




## Gliederung


</br>
</br>


.xlarge[
1. [Einleitung: Wissenschaft als Gerechtigkeitsprojekt](#einleitung)

2. [Teil 1: Eine binäre UV](#teil-1)

3. [Teil 2: Eine metrische plus eine nominale UV](#teil-2)

4. [Teil 3: Eine nominale UV mit mehreren Stufen](#teil-3)

4. [Teil 4: Mehrere metrische UV](#teil-4)

3. [Hinweise](#hinweise)
]

---




```{r QM2-Thema6-Intro, eval = TRUE, child="children/Thema6-Intro.Rmd"}
```



```{r QM2-Thema6-Intro, eval = TRUE, child="children/Thema6-Teil1.Rmd"}
```



```{r QM2-Thema6-Intro, eval = TRUE, child="children/Thema6-Teil2.Rmd"}
```




```{r QM2-Thema6-Intro, eval = TRUE, child="children/Thema6-Teil3.Rmd"}
```


```{r QM2-Thema6-Intro, eval = TRUE, child="children/Thema6-Teil4.Rmd"}
```



```{r QM2-Thema4-Gaussmodelle-3, eval = TRUE, child="children/Hinweise.Rmd"}
```
