---
params:
  kapitel_name: "Lineare Modelle" 
  kapitel_nr: 5

title: "`r params$kapitel_name`"
subtitle: "`r  paste0('Kapitel ', params$kapitel_nr)`"
#date: WiSe 21

#institute: AWM, HS Ansbach
output:
  xaringan::moon_reader:
    keep_md: false
    css: ["my-css.css","xaringan-themer.css",  "hygge", "default-fonts"]
    lib_dir: libs
    seal: true
    nature:
      titleSlideClass: ["right", "bottom", "test"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

name: gliederung


```{r QM2-Thema4-Gaussmodelle-1, child="children/Setup.Rmd"}
```


```{r}
book <- "Rethink, Kap. 4.4, ROS, Kap. 9.2"
```



```{r}
knitr::opts_chunk$set(
   fig.path = paste0("Kapitel_", params$kapitel_nr,"_chunk-img/")
   )
```



## Gliederung


</br>


.xxlarge[
1. [Teil 1: Die Post-Verteilung der Regression berechnen](#teil-1)

2. [Teil 2: Die Post-Verteilung befragen](#teil-2)

3. [Teil 3: Die PPV befragen](#teil-3)

4. [Hinweise](#hinweise)
]

---

```{r QM2-Thema4-Gaussmodelle-2, eval = TRUE, child="children/Post-Regression.Rmd"}
```



```{r QM2-Thema4-Gaussmodelle-3, eval = TRUE, child="children/Post-Regression-befragen.Rmd"}
```


```{r QM2-Thema4-Gaussmodelle-4, eval = TRUE, child="children/QM2-Thema5-Teil3.Rmd"}
```


```{r QM2-Thema4-Gaussmodelle-5, eval = TRUE, child="children/Hinweise.Rmd"}
```
