---
title: TEST

output:
  xaringan::moon_reader:
#    css: ["xaringan-themer.css"]

    css: [default, default-fonts, hygge ]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

#numbersections: yes
csquotes: TRUE     
---




```{r QM2-Thema4-Gaussmodelle-1, child="children/Setup.Rmd"}
```


```{r}
rethink_chap <- "3"
```


## Zur Erinnerung: Quantile

Beispiel: Wie groß sind die Studentis ([Quelle des Datensatzes](https://rdrr.io/cran/openintro/man/speed_gender_height.html))? Hier die Quantile für 25%, 50%, 75%:

```{r QM2-Thema3-Teil1-5, echo = FALSE}
library(openintro)
data(speed_gender_height)

height_summary <- 
  speed_gender_height %>% 
  drop_na(height) %>% 
  summarise(q25 = quantile(height, prob = .25),
            q50 = quantile(height, prob = .5),
            q75 = quantile(height, prob = .75))

height_summary %>% 
  gt()
```

Visualisierung der Quantile:

```{r QM2-Thema3-Teil1-6, results = "hold", fig.width = 8, fig.asp = .4, cache= FALSE}
p1 <- speed_gender_height %>% 
  ggplot() +
  aes(x = 1, y = height) +
  geom_boxplot() +
  labs(x = "",
       y = "Größe in Inch",
       title = "Die Box zeigt das 25%-, 50%- und 75%-Quantil")

height_summary_long <- 
  height_summary %>% 
  pivot_longer(everything(),
               names_to = "q",
               values_to = "height")

p2 <- speed_gender_height %>% 
  ggplot() +
  aes(x = height) +
  geom_histogram() +
  geom_vline(data = height_summary_long,
             aes(xintercept = height)) +
  geom_text(data = height_summary_long,
             aes(x = height+1,
                 y = 0,
                 label = paste0(q, ": ",height)),
             angle = 90,
            hjust = 0,
            color = "white"
             ) +
  labs(title = "Die vertikalen Striche zeigen die Quantile")

p1+p2
```

