
<style>

.center2 {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}

</style>





```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


  


```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(
  fig.pos = 'H',
  fig.asp = 0.618,
  fig.align='center',
  fig.width = 5,
  out.width = "100%",
  fig.cap = "", 
 # fig.path = "chunk-img/",
  dpi = 300,
  #tidy = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.show = "hold")

knitr::opts_knit$set(
 #base.dir = paste0(here::here(),"/img"),
  root.dir = rprojroot::find_rstudio_root_file()
)

knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)

options("knitr.graphics.auto_pdf" = FALSE)
```




```{r xaringan-themer, include = FALSE}
library(xaringanthemer)

style_mono_light(
  base_color = "#23395b",
  header_font_google = xaringanthemer::google_font("Yanone Kaffeesatz"),
  link_color = "#F92672",
  text_font_size = "1rem",
  text_slide_number_color = "#727A86",
  header_h1_font_size = "2.75rem",
  header_h2_font_size = "2.25rem",
  header_h3_font_size = "1.75rem"
)

```



```{r load-libs, echo = FALSE}
library(tidyverse)
library(knitr)
#library(kableExtra)
#library(nomnoml)
#library(ggdag)
library(patchwork)
library(gt)
#library(emojifont)
library(RefManageR)
library(tidybayes)
library(xaringanExtra)
library(scales)
library(rstanarm)
library(xaringanthemer)
```

```{r source-funs}
source("R-Code/img.R")
```




```{r bib, cache=FALSE}
BibOptions(check.entries = FALSE, 
           bib.style = "authoryear", 
           style = "markdown",
           max.names = 5,
           dashed = TRUE,
           no.print.fields = 
             c("url", "page","isbn", "location", "urldate", "note", "urldate", "issn")
           )
bib_file <- "bib.bib"
bib <- ReadBib(bib_file)
```



```{r ggplottheme}
theme_set(theme_xaringan(text_font_size = 10,
                         title_font_size = 12))

 # +
 #  theme(  axis.title = element_text(size = 8),
 #          legend.title = element_text(size = 6))

```


```{r xaringan-extra, echo=FALSE}
use_xaringan_extra(c("tile_view", "tachyons"))
#use_xaringan_extra(c("tachyons"))

#xaringanExtra::use_animate_all("slide_left")
```



```{r xaringanExtra-scribble, echo=FALSE, eval = FALSE}
xaringanExtra::use_scribble()
```



```{r rstan-options}
rstan::rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```
